/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paquetebibloteca;

/**
 *
 * @author Genesis
 */
public class Proyecto extends javax.swing.JFrame {

    /**
     * Creates new form Proyecto
     */
    public Proyecto() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbTitulo = new javax.swing.JLabel();
        BtnUsuario = new javax.swing.JButton();
        BtnLibros = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        BtnPrestamos = new javax.swing.JButton();
        jlbFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbTitulo.setBackground(new java.awt.Color(153, 153, 255));
        jlbTitulo.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jlbTitulo.setText("     Bienvenidos a la Bibloteca");
        jlbTitulo.setName(""); // NOI18N
        getContentPane().add(jlbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 380, 30));

        BtnUsuario.setBackground(new java.awt.Color(255, 204, 204));
        BtnUsuario.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        BtnUsuario.setText("Usuarios");
        BtnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(BtnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 130, 30));

        BtnLibros.setBackground(new java.awt.Color(255, 204, 204));
        BtnLibros.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        BtnLibros.setText("Libros");
        BtnLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLibrosActionPerformed(evt);
            }
        });
        getContentPane().add(BtnLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 130, 30));

        BtnSalir.setBackground(new java.awt.Color(255, 204, 204));
        BtnSalir.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 130, -1));

        BtnPrestamos.setBackground(new java.awt.Color(255, 204, 204));
        BtnPrestamos.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        BtnPrestamos.setText("Prestamos");
        BtnPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrestamosActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 130, 30));

        jlbFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo2.png"))); // NOI18N
        jlbFondo.setText("jLabel2");
        getContentPane().add(jlbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUsuarioActionPerformed
        // Boton de Lllamar la ventana Datos
        dispose();
        new DatosUsuario().setVisible(true);
    }//GEN-LAST:event_BtnUsuarioActionPerformed

    private void BtnLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLibrosActionPerformed
        // Boton para Llamar la ventana Libros
        dispose();
        new Agregar().setVisible(true);
    }//GEN-LAST:event_BtnLibrosActionPerformed

    private void BtnPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrestamosActionPerformed
        // Boton para Llamar la ventana Prestamos
        dispose();
        new DatosPrestamo().setVisible(true);
    }//GEN-LAST:event_BtnPrestamosActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        // Boton para Salir
        System.exit(0);
    }//GEN-LAST:event_BtnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLibros;
    private javax.swing.JButton BtnPrestamos;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton BtnUsuario;
    private javax.swing.JLabel jlbFondo;
    private javax.swing.JLabel jlbTitulo;
    // End of variables declaration//GEN-END:variables
}
