/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paquetebibloteca;

import static Paquetebibloteca.Agregar.intro;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Genesis
 */
public class Usuarios extends javax.swing.JFrame {
    public final String Usuario = "Usuario.txt";

    /**
     * Creates new form Usuarios
     */
    public Usuarios() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbTitulo4 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jblNombre = new javax.swing.JLabel();
        BtnRegresar = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        BtnGuardar = new javax.swing.JButton();
        jTextFieldApellido = new javax.swing.JTextField();
        jTextFieldCedula = new javax.swing.JTextField();
        jTextFieldNacionalidad = new javax.swing.JTextField();
        jblApellido = new javax.swing.JLabel();
        jblCedula = new javax.swing.JLabel();
        jblNacionalidad = new javax.swing.JLabel();
        jblTelefono = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jblCorreo = new javax.swing.JLabel();
        jblDirrecion = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextFieldCorreo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        btnRegistrar = new javax.swing.JButton();
        jlbFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbTitulo4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jlbTitulo4.setText("Registrar Usuario");
        getContentPane().add(jlbTitulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 120, -1));

        jTextFieldNombre.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        jTextFieldNombre.setToolTipText("Ingrese Nombre");
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 140, -1));

        jblNombre.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jblNombre.setText("Nombre:");
        getContentPane().add(jblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 60, 20));

        BtnRegresar.setBackground(new java.awt.Color(255, 102, 102));
        BtnRegresar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BtnRegresar.setText("Regresar");
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        BtnSalir.setBackground(new java.awt.Color(255, 102, 102));
        BtnSalir.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, -1, -1));

        BtnGuardar.setBackground(new java.awt.Color(255, 102, 102));
        BtnGuardar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));

        jTextFieldApellido.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        jTextFieldApellido.setToolTipText("Ingrese Apellido");
        jTextFieldApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 140, -1));

        jTextFieldCedula.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        jTextFieldCedula.setToolTipText("Ingrese Cedula");
        jTextFieldCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCedulaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 140, -1));

        jTextFieldNacionalidad.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        jTextFieldNacionalidad.setToolTipText("Ingrese Nacionalidad");
        getContentPane().add(jTextFieldNacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 140, -1));

        jblApellido.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jblApellido.setText("Apellido:");
        getContentPane().add(jblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 60, 20));

        jblCedula.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jblCedula.setText("Cedula:");
        getContentPane().add(jblCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 50, 20));

        jblNacionalidad.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jblNacionalidad.setText("Nacionalidad:");
        getContentPane().add(jblNacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 90, 20));

        jblTelefono.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jblTelefono.setText("Teléfono:");
        getContentPane().add(jblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 60, -1));

        jTextFieldTelefono.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        jTextFieldTelefono.setToolTipText("Ingrese Telefono");
        getContentPane().add(jTextFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 140, -1));

        jblCorreo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jblCorreo.setText("Correo:");
        getContentPane().add(jblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 50, 20));

        jblDirrecion.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jblDirrecion.setText("Dirección:");
        getContentPane().add(jblDirrecion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 90, -1));

        jTextFieldDireccion.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        jTextFieldDireccion.setToolTipText("Ingrese Direccion");
        getContentPane().add(jTextFieldDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 140, -1));

        jTextFieldCorreo.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        jTextFieldCorreo.setToolTipText("Ingrese Correo");
        getContentPane().add(jTextFieldCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 140, -1));

        Tabla.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Cedula", "Nacionalidad", "Telefono", "Direccion", "Correo"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 660, 100));

        btnRegistrar.setBackground(new java.awt.Color(255, 102, 102));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, -1, -1));

        jlbFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo3.png"))); // NOI18N
        jlbFondo.setText("jLabel1");
        getContentPane().add(jlbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidoActionPerformed

    private void jTextFieldCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCedulaActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        // Boton para Salir
        System.exit(0);
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        // Boton para Regresar a la ventana Datos
        dispose();
        new DatosUsuario().setVisible(true);
    }//GEN-LAST:event_BtnRegresarActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        // Registrar los datos
        String nombre = jTextFieldNombre.getText().trim();
        String apellido = jTextFieldApellido.getText().trim();
        String cedula = jTextFieldCedula.getText().trim();
        String nacionalidad = jTextFieldNacionalidad.getText().trim();
        String telefono = jTextFieldTelefono.getText().trim();
        String correo = jTextFieldCorreo.getText().trim();
        String direccion = jTextFieldDireccion.getText().trim();
        
        JOptionPane.showMessageDialog(null,"Datos Guardados");
        
           try {
            DataOutputStream dos = new DataOutputStream(new FileOutputStream(Usuario, true));
            DataInputStream dis = new DataInputStream(new FileInputStream(Usuario));
            intro(dos, nombre,apellido,cedula,nacionalidad,telefono,correo,direccion );

        } catch (Exception e) {
            e.getStackTrace();
        }
        
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // Boton para agregar datos
        DefaultTableModel modelo=(DefaultTableModel) Tabla.getModel();
         Object [] fila=new Object[7]; 
        fila[0]=jTextFieldNombre.getText(); 
        fila[1]=jTextFieldApellido.getText(); 
        fila[2]=jTextFieldCedula.getText(); 
        fila[3]=jTextFieldNacionalidad.getText(); 
        fila[4]=jTextFieldTelefono.getText(); 
        fila[5]=jTextFieldDireccion.getText();
        fila[6]=jTextFieldCorreo.getText();
        
          modelo.addRow(fila); 
           Tabla.setModel(modelo); 
           
         JOptionPane.showMessageDialog(null,"Datos Guardados");
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldCedula;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldNacionalidad;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JLabel jblApellido;
    private javax.swing.JLabel jblCedula;
    private javax.swing.JLabel jblCorreo;
    private javax.swing.JLabel jblDirrecion;
    private javax.swing.JLabel jblNacionalidad;
    private javax.swing.JLabel jblNombre;
    private javax.swing.JLabel jblTelefono;
    private javax.swing.JLabel jlbFondo;
    private javax.swing.JLabel jlbTitulo4;
    // End of variables declaration//GEN-END:variables
public static void intro(DataOutputStream dos, String nombre,String apellido, String cedula, String nacionalidad, String telefono, String correo, String direccion) throws IOException {
        dos.writeUTF(nombre + "\n");
        dos.writeUTF(apellido + "\n");
        dos.writeUTF(cedula + "\n");
        dos.writeUTF(nacionalidad + "\n");
        dos.writeUTF(telefono + "\n");
        dos.writeUTF(correo + "\n");
        dos.writeUTF(direccion + "\n");

    }
}
